# Generated by Django 4.2.1 on 2023-06-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SynchronUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='synchron_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synchron_users', to='api.position')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='StandupCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standup_date', models.DateField(auto_now_add=True)),
                ('release_cycle', models.CharField(max_length=255)),
                ('sprint_id', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_cards', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCardUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standup_card_updates', to='api.synchronuser')),
                ('standup_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_card_updates', to='api.standupcard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='standupcard',
            constraint=models.UniqueConstraint(fields=('release_cycle', 'sprint_id'), name='standup_card_constraint'),
        ),
    ]
