# Generated by Django 4.2.1 on 2023-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='standupcard',
            name='standup_card_constraint',
        ),
        migrations.AddConstraint(
            model_name='standupcard',
            constraint=models.UniqueConstraint(fields=('team', 'release_cycle', 'sprint_id'), name='standup_card_constraint'),
        ),
    ]
